const prepositions = [
  "about", "above", "across", "after", "against",
  "along", "among", "around", "as", "at",
  "before", "behind", "below", "beneath", "beside",
  "between", "beyond", "by", "concerning", "considering",
  "despite", "down", "during", "except", "for",
  "from", "in", "inside", "into", "like",
  "near", "of", "off", "on", "onto",
  "out", "outside", "over", "past", "regarding",
  "since", "through", "throughout", "to", "toward",
  "under", "underneath", "until", "up", "upon",
  "with", "within", "without", "according to", "ahead of",
  "apart from", "as for", "as well as", "because of", "by means of",
  "close to", "due to", "except for", "far from", "in addition to",
  "in case of", "in front of", "in place of", "in spite of", "instead of",
  "near to", "next to", "on account of", "on behalf of", "on top of",
  "out of", "prior to", "such as", "thanks to", "together with",
  "up to", "with regard to", "with respect to", "aboard", "amid",
  "amidst", "apropos", "atop", "barring", "circa",
  "excepting", "following", "given", "including", "notwithstanding",
  "per", "plus", "qua", "re", "save",
  "than", "till", "versus", "via"
];